### ISSUE TITLE
choco가 뭔가요?!

### ISSUE THREAD

**Issue by doyi0107** [doyi0107/React_native_study#1]
글을 보니 choco는 각 환경마다 따로 설치하는데 choco가 하는 역할이 정확히 뭔가요?

**Comment by kalmaho** [comment]
choco는 윈도우용 패키지 관리자 입니다.
프로그램을 설치하려면 직접 프로그램을 검색하고 찾아서 설치해야합니다.
하지만 choco를 사용하면, 커맨드에 프로그램 이름만 입력하면 자동으로 설치해줍니다.
